//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kharazmi.Net.Http {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShareResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShareResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kharazmi.Net.Http.ShareResource", typeof(ShareResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can&apos;t be null..
        /// </summary>
        internal static string ArgumentNullException {
            get {
                return ResourceManager.GetString("ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem accessing the Token Response endpoint.\nError Message: {0}.
        /// </summary>
        internal static string DiscoveryDocumentResponse {
            get {
                return ResourceManager.GetString("DiscoveryDocumentResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem accessing the Token Response endpoint.\nError Message: {0}.
        /// </summary>
        internal static string DiscoveryResponse {
            get {
                return ResourceManager.GetString("DiscoveryResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidCode.
        /// </summary>
        internal static string ErrorInvalidCode {
            get {
                return ResourceManager.GetString("ErrorInvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No temp cookie.
        /// </summary>
        internal static string ErrorInvalidCookie {
            get {
                return ResourceManager.GetString("ErrorInvalidCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid nonce.
        /// </summary>
        internal static string ErrorInvalidNonce {
            get {
                return ResourceManager.GetString("ErrorInvalidNonce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid state.
        /// </summary>
        internal static string ErrorInvalidState {
            get {
                return ResourceManager.GetString("ErrorInvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token.
        /// </summary>
        internal static string ErrorInvalidToken {
            get {
                return ResourceManager.GetString("ErrorInvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthorizationPolicy must have at least one requirement..
        /// </summary>
        internal static string Exception_AuthorizationPolicyEmpty {
            get {
                return ResourceManager.GetString("Exception_AuthorizationPolicyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AuthorizationPolicy named: &apos;{0}&apos; was not found..
        /// </summary>
        internal static string Exception_AuthorizationPolicyNotFound {
            get {
                return ResourceManager.GetString("Exception_AuthorizationPolicyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one role must be specified..
        /// </summary>
        internal static string Exception_RoleRequirementEmpty {
            get {
                return ResourceManager.GetString("Exception_RoleRequirementEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IntrospectionRequest {
            get {
                return ResourceManager.GetString("IntrospectionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication fails for an authentication stream and cannot be retried..
        /// </summary>
        internal static string InvalidCredentialException {
            get {
                return ResourceManager.GetString("InvalidCredentialException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can&apos;t be null..
        /// </summary>
        internal static string NullReferenceException {
            get {
                return ResourceManager.GetString("NullReferenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem accessing the Token Response endpoint.\nError Message: {0}\nHttp Error StatusCode: {1}.
        /// </summary>
        internal static string TokenResponse {
            get {
                return ResourceManager.GetString("TokenResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem accessing the TokenRevocation endpoint\nError Message: {0}\nHttp Error StatusCode: {1}.
        /// </summary>
        internal static string TokenRevocationResponse {
            get {
                return ResourceManager.GetString("TokenRevocationResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem accessing the UserInfo endpoint.\nError Message: {0}\nHttp Error StatusCode: {0}.
        /// </summary>
        internal static string UserInfoResponse {
            get {
                return ResourceManager.GetString("UserInfoResponse", resourceCulture);
            }
        }
    }
}
