//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc.Utility.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShareResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShareResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mvc.Utility.Core.ShareResources", typeof(ShareResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        internal static string Accessdenied {
            get {
                return ResourceManager.GetString("Accessdenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can&apos;t be null..
        /// </summary>
        internal static string ArgumentNullException {
            get {
                return ResourceManager.GetString("ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        internal static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort Wiederholung.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HMP Software Solutions GmbH. All Rights reserved..
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem accessing the Token Response endpoint.\nError Message: {0}.
        /// </summary>
        internal static string DiscoveryDocumentResponse {
            get {
                return ResourceManager.GetString("DiscoveryDocumentResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add decision papers.
        /// </summary>
        internal static string DisplayAddDocuments {
            get {
                return ResourceManager.GetString("DisplayAddDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag-and-drop the decision papers here to upload them.
        /// </summary>
        internal static string DisplyDropFilesHere {
            get {
                return ResourceManager.GetString("DisplyDropFilesHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you accidentally tried to double post..
        /// </summary>
        internal static string DuplicateRequest {
            get {
                return ResourceManager.GetString("DuplicateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON GET is not allowed..
        /// </summary>
        internal static string ErrorAllowGetJosn {
            get {
                return ResourceManager.GetString("ErrorAllowGetJosn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie dürfen keine HTML-Tags verwenden..
        /// </summary>
        internal static string ErrorAllowHtmlTag {
            get {
                return ResourceManager.GetString("ErrorAllowHtmlTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property is a combination of &quot;AuthorizeEndpoint&quot; and &quot;BaseAddress&quot;.
        ///Make sure the correct address is entered..
        /// </summary>
        internal static string ErrorInvalidAuthorizeEndpoint {
            get {
                return ResourceManager.GetString("ErrorInvalidAuthorizeEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This server could not verify your authorized to access the doument requested..
        /// </summary>
        internal static string ErrorMessageAuthorizationRequired401 {
            get {
                return ResourceManager.GetString("ErrorMessageAuthorizationRequired401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server returned an invalid or incomplete response..
        /// </summary>
        internal static string ErrorMessageBadGateway502 {
            get {
                return ResourceManager.GetString("ErrorMessageBadGateway502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your browser send a request that server could not understand..
        /// </summary>
        internal static string ErrorMessageBadRequest400 {
            get {
                return ResourceManager.GetString("ErrorMessageBadRequest400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        internal static string ErrorMessageConfirmPassword {
            get {
                return ResourceManager.GetString("ErrorMessageConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the desired number in the correct format (for example [12/11]).
        /// </summary>
        internal static string ErrorMessageDecimalNumber {
            get {
                return ResourceManager.GetString("ErrorMessageDecimalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your don&apos;t have permission to access on this server..
        /// </summary>
        internal static string ErrorMessageForbidden403 {
            get {
                return ResourceManager.GetString("ErrorMessageForbidden403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gateway did not receive a timely response from the upstream server..
        /// </summary>
        internal static string ErrorMessageGatewayTimeOut504 {
            get {
                return ResourceManager.GetString("ErrorMessageGatewayTimeOut504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server encountered an internal error or misconfiguration and was unable to complete your request..
        /// </summary>
        internal static string ErrorMessageInternalServerError500 {
            get {
                return ResourceManager.GetString("ErrorMessageInternalServerError500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        internal static string ErrorMessageInvalidLoginAttempt {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found or code is not valid..
        /// </summary>
        internal static string ErrorMessageInvalidUser {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is locked! Please after  {0}  minute Try again.
        /// </summary>
        internal static string ErrorMessageLockedOut {
            get {
                return ResourceManager.GetString("ErrorMessageLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}can not be less than {1} character..
        /// </summary>
        internal static string ErrorMessageMinStringLength {
            get {
                return ResourceManager.GetString("ErrorMessageMinStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request URL was not found on this server..
        /// </summary>
        internal static string ErrorMessageNotFound404 {
            get {
                return ResourceManager.GetString("ErrorMessageNotFound404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The browser can not to redirect..
        /// </summary>
        internal static string ErrorMessageRedirection301 {
            get {
                return ResourceManager.GetString("ErrorMessageRedirection301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your browser didn&apos;t send a complete request in time..
        /// </summary>
        internal static string ErrorMessageRequestTimeOut408 {
            get {
                return ResourceManager.GetString("ErrorMessageRequestTimeOut408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        internal static string ErrorMessageRequired {
            get {
                return ResourceManager.GetString("ErrorMessageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the numbers in the password..
        /// </summary>
        internal static string ErrorMessageRequireDigit {
            get {
                return ResourceManager.GetString("ErrorMessageRequireDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use lowercase letters for passwords..
        /// </summary>
        internal static string ErrorMessageRequireLowercase {
            get {
                return ResourceManager.GetString("ErrorMessageRequireLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For security reasons, use at least one non-numeric password character..
        /// </summary>
        internal static string ErrorMessageRequireNonLetterOrDigit {
            get {
                return ResourceManager.GetString("ErrorMessageRequireNonLetterOrDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use uppercase letters for passwords..
        /// </summary>
        internal static string ErrorMessageRequireUppercase {
            get {
                return ResourceManager.GetString("ErrorMessageRequireUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum value for {0} should be between {2} and {1}..
        /// </summary>
        internal static string ErrorMessageStringLength {
            get {
                return ResourceManager.GetString("ErrorMessageStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path not specified..
        /// </summary>
        internal static string ErrorPathFileNull {
            get {
                return ResourceManager.GetString("ErrorPathFileNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing document failed!.
        /// </summary>
        internal static string ErrorRemoveDocumentFail {
            get {
                return ResourceManager.GetString("ErrorRemoveDocumentFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The owin environment dictionary was null.
        /// </summary>
        internal static string ErrorTheOwinEnvironmentDictionaryWasNull {
            get {
                return ResourceManager.GetString("ErrorTheOwinEnvironmentDictionaryWasNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirection Problem.
        /// </summary>
        internal static string ErrorTileRedirection301 {
            get {
                return ResourceManager.GetString("ErrorTileRedirection301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Required.
        /// </summary>
        internal static string ErrorTitleAuthorizationRequired401 {
            get {
                return ResourceManager.GetString("ErrorTitleAuthorizationRequired401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Gateway.
        /// </summary>
        internal static string ErrorTitleBadGateway502 {
            get {
                return ResourceManager.GetString("ErrorTitleBadGateway502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        internal static string ErrorTitleBadRequest400 {
            get {
                return ResourceManager.GetString("ErrorTitleBadRequest400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden.
        /// </summary>
        internal static string ErrorTitleForbidden403 {
            get {
                return ResourceManager.GetString("ErrorTitleForbidden403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway Time-Out.
        /// </summary>
        internal static string ErrorTitleGatewayTimeOut504 {
            get {
                return ResourceManager.GetString("ErrorTitleGatewayTimeOut504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error.
        /// </summary>
        internal static string ErrorTitleInternalServerError500 {
            get {
                return ResourceManager.GetString("ErrorTitleInternalServerError500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        internal static string ErrorTitleNotFound404 {
            get {
                return ResourceManager.GetString("ErrorTitleNotFound404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Time-Out.
        /// </summary>
        internal static string ErrorTitleRequestTimeOut408 {
            get {
                return ResourceManager.GetString("ErrorTitleRequestTimeOut408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload document failed!.
        /// </summary>
        internal static string ErrorUploadDocumentFail {
            get {
                return ResourceManager.GetString("ErrorUploadDocumentFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthorizationOptions must not be null.  Your resource authorization may be set up incorrectly..
        /// </summary>
        internal static string Exception_AuthorizationOptionsMustNotBeNull {
            get {
                return ResourceManager.GetString("Exception_AuthorizationOptionsMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthorizationPolicy must have at least one requirement..
        /// </summary>
        internal static string Exception_AuthorizationPolicyEmpty {
            get {
                return ResourceManager.GetString("Exception_AuthorizationPolicyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AuthorizationPolicy named: &apos;{0}&apos; was not found..
        /// </summary>
        internal static string Exception_AuthorizationPolicyNotFound {
            get {
                return ResourceManager.GetString("Exception_AuthorizationPolicyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AuthorizationPolicy named: &apos;{0}&apos; was not found..
        /// </summary>
        internal static string Exception_AuthorizationPolicyNotFound1 {
            get {
                return ResourceManager.GetString("Exception_AuthorizationPolicyNotFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please setup owin resource authorization in your startup file.
        /// </summary>
        internal static string Exception_PleaseSetupOwinResourceAuthorizationInYourStartupFile {
            get {
                return ResourceManager.GetString("Exception_PleaseSetupOwinResourceAuthorizationInYourStartupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one role must be specified..
        /// </summary>
        internal static string Exception_RoleRequirementEmpty {
            get {
                return ResourceManager.GetString("Exception_RoleRequirementEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        internal static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported JSONToken.
        /// </summary>
        internal static string FormatError_UnsupportedJSONToken {
            get {
                return ResourceManager.GetString("FormatError_UnsupportedJSONToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwarding of responsibility.
        /// </summary>
        internal static string ForwardingOfResponsibility {
            get {
                return ResourceManager.GetString("ForwardingOfResponsibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geh Zurück.
        /// </summary>
        internal static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Home.
        /// </summary>
        internal static string GoHome {
            get {
                return ResourceManager.GetString("GoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        internal static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All employees are required to document in writing and archive the basis for business decisions regarding the selection of suppliers and product ranges as well as communications with suppliers. Use the following archiving function to archive documents related to decisions..
        /// </summary>
        internal static string HomeTeaser {
            get {
                return ResourceManager.GetString("HomeTeaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid.
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t cast that value to a {0}!.
        /// </summary>
        internal static string InvalidCastException {
            get {
                return ResourceManager.GetString("InvalidCastException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid output format.
        /// </summary>
        internal static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization failed for user: {0}.
        /// </summary>
        internal static string LogAuthorizationFailedForUser {
            get {
                return ResourceManager.GetString("LogAuthorizationFailedForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization was successful for user: {0}.
        /// </summary>
        internal static string LogAuthorizationSucceededForUser {
            get {
                return ResourceManager.GetString("LogAuthorizationSucceededForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your account by clicking.
        /// </summary>
        internal static string MessageConfirmEmail {
            get {
                return ResourceManager.GetString("MessageConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is null..
        /// </summary>
        internal static string NullReferenceException {
            get {
                return ResourceManager.GetString("NullReferenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter is required.
        /// </summary>
        internal static string ParameterRequired {
            get {
                return ResourceManager.GetString("ParameterRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language....
        /// </summary>
        internal static string PlaceHolderSelectLanguage {
            get {
                return ResourceManager.GetString("PlaceHolderSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string Rememberme {
            get {
                return ResourceManager.GetString("Rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Expire.
        /// </summary>
        internal static string SessionExpire {
            get {
                return ResourceManager.GetString("SessionExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session time has ended. The page is refresh for up to 5 seconds..
        /// </summary>
        internal static string SessionExpireMessage {
            get {
                return ResourceManager.GetString("SessionExpireMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem accessing the Token Response endpoint.\nError Message: {0}\nHttp Error StatusCode: {1}.
        /// </summary>
        internal static string TokenResponse {
            get {
                return ResourceManager.GetString("TokenResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not obtain locks.
        /// </summary>
        internal static string TryLockError {
            get {
                return ResourceManager.GetString("TryLockError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown property {0}.
        /// </summary>
        internal static string UnknownProperty {
            get {
                return ResourceManager.GetString("UnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Completed.
        /// </summary>
        internal static string UploadCompleted {
            get {
                return ResourceManager.GetString("UploadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Files.
        /// </summary>
        internal static string UploadFiles {
            get {
                return ResourceManager.GetString("UploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem accessing the UserInfo endpoint.\nError Message: {0}\nHttp Error StatusCode: {0}.
        /// </summary>
        internal static string UserInfoResponse {
            get {
                return ResourceManager.GetString("UserInfoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
